apiVersion: batch/v1
kind: Job
metadata:
  generateName: fairing-job-
  name: fairing-job
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        job-name: fairing-job
      name: fairing-deployer
    spec:
      containers:
        command: ["/bin/bash"]
        args: ['-c', 'pip install boto3 && python main_minio.py']
        env:
        - name: FAIRING_RUNTIME
          value: "1"
        image: fairing-job-image
        imagePullPolicy: IfNotPresent
        name: fairing-job
        # Need to use root to run pip install
        securityContext:
          runAsUser: 0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /app/
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
