apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: fairing-build-deploy-pipeline
spec:
  params:
  - description: The sub directory of the build context used by Kaniko
    name: context_sub_dir
    type: string
    default: ""
  - description: The sub directory of the dockerfile to build
    name: dockerfile_sub_dir
    type: string
    default: ""
  - description: The sub directory of the job yaml file
    name: job_yaml_sub_dir
    type: string
    default: ""
  resources:
  # Pipeline has 1 image resource and 1 cluster resource
  # builtImage - Image name to build and push. e.g. index.docker.io/XXX/fairing-job:XXX
  # remote_kubeconfig - Remote kubeconfig to deploy fairing job
  - name: builtImage
    type: image
  - name: remote_kubeconfig
    type: cluster
  workspaces:
   # Workspace has 1 volume and 1 configMap to mount
   # fairing-build - Mounted workspace to store build Kanico context, Dockerfile and Job yaml
   # docker-registry-config - Mounted configMap of user's docker config for image push
  - name: fairing-build
  - name: docker-registry-config
  tasks:
  - name: fairing-build-push
    params:
    - name: context_sub_dir
      value: "$(params.context_sub_dir)"
    - name: dockerfile_sub_dir
      value: "$(params.dockerfile_sub_dir)"
    resources:
      outputs:
      - name: builtImage
        resource: builtImage
    workspaces:
      - name: fairing-build
        workspace: fairing-build
      - name: docker-registry-config
        workspace: docker-registry-config
    taskRef:
      name: fairing-build-push
      kind: namespaced
  - name: fairing-job-deploy
    runAfter:
    - fairing-build-push
    params:
    - name: job_yaml_sub_dir
      value: "$(params.job_yaml_sub_dir)"
    resources:
      inputs:
      - name: builtImage
        resource: builtImage
      - name: remote_kubeconfig
        resource: remote_kubeconfig
    workspaces:
    - name: fairing-build
      workspace: fairing-build
    taskRef:
      name: fairing-job-deploy
      kind: namespaced