# TODO(mochiliu3000): As Tekton task is runing in container, to make it easy for now, 
# we assume fairing has already generated context and dockerfile, 
# we then trigger the following tekton task to build and push image
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fairing-build-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: fairing-build-push
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  inputs:
    params:
    - description: The sub directory of the build context used by Kaniko
      name: context_sub_dir
      type: string
    - description: The sub directory of the dockerfile to build
      name: dockerfile_sub_dir
      type: string
  outputs:
    resources:
    - name: builtImage
      type: image
  # https://github.com/tektoncd/pipeline/blob/release-v0.10.x/examples/taskruns/workspace.yaml
  workspaces:
  - name: fairing-build
    description: fairing build files
    mountPath: /workspace/fairing-build
  - name: docker-registry-config
    description: docker config file
    mountPath: /kaniko/.docker
  steps:
  # https://github.com/GoogleContainerTools/kaniko/tree/v0.14.0#kaniko-build-contexts
  - name: fairing-build-push
    image: gcr.io/kaniko-project/executor:v0.14.0
    # image: ubuntu
    # env:
    # - name: "DOCKER_CONFIG"
    #   value: $(workspaces.docker-registry-config.path)
    command:
    - /kaniko/executor
    - --dockerfile=$(workspaces.fairing-build.path)/$(inputs.params.dockerfile_sub_dir)
    - --context=dir://$(workspaces.fairing-build.path)/$(inputs.params.context_sub_dir)
    - --destination=$(outputs.resources.builtImage.url)
    # script: echo $(outputs.resources.builtImage.url) && echo $(workspaces.fairing-build.path)
    requests:
      cpu: 2
      memory: 4Gi